### ISSUE TITLE
cannot react property 'replace' of undefined when using react-native link

### ISSUE THREAD

**Issue by macrozone** [rhdeck/react-native-pod#1]
i added react-native-pod to my project and got this error:

```
/path/to/project/node_modules/react-native-pod/lib/findPodTargetLine.js:4
  const targetName = projectName.replace('.xcodeproj', '');
                                 ^
TypeError: Cannot read property 'replace' of undefined
    at findPodTargetLine (/path/to/project/node_modules/react-native-pod/lib/findPodTargetLine.js:4:34)
    at getLinesToAddEntry (/path/to/project/node_modules/react-native-pod/lib/registerPod.js:24:30)
    at registerPod (/path/to/project/node_modules/react-native-pod/lib/registerPod.js:14:27)
    at Object.keys.map (/path/to/project/node_modules/react-native-pod/bin/postlink.js:32:13)

```

**Comment by rhdeck** [comment]
How did you resolve the issue?

**Comment by macrozone** [comment]
@rhdeck this specific error did not happen anymore, but i had other problems with xcode and cocoapods

**Comment by rhdeck** [comment]
Would love to know more about them if you have time/inclination. The intent of the project is to make it easy (easier?) to integrate RN SLs with Cocoapods.  SO understanding other issues people run into lets me further the mission! 

Another utility that helps with working with RN and cocoapods: `yarn add react-native-xcode`. It automatically selects whether to open the xcworkspace or the xcodeproj every time you run it as "react-native xcode" from your app project directory.
