### ISSUE TITLE
when next push ?

### ISSUE THREAD

**Issue by qtdc1229** [rhdeck/react-native-pod#2]
hi, I find that you coded this project for quick help use cocoapods in ReactNative project , it's so cool .    
but  modify podfile it's not work now . I want know what's your plan ?

**Comment by rhdeck** [comment]
Can you share a little more info about your problem? For example, the project (if open source) or the podfile and maybe the package.json that is not working?

**Comment by rhdeck** [comment]
Closing from lack of response. Can re-open if more data comes in.
