### ISSUE TITLE
Cannot find module '../lib/addpod.js'

### ISSUE THREAD

**Issue by c100k** [rhdeck/react-native-pod#5]
Hi,

I'm running the build in a docker container and I have the following error :

> Cannot find module '../lib/addpod.js'

No error when running on my Mac. When we look at the source, the file name is `addPod.js`.

Is there a bug or am I missing something ?

Thanks

**Comment by rhdeck** [comment]
Fixed, committed, pushed to NPM. 

Background: macOS file system forgives case errors. e.g. your ~/Documents/GitHub directory can be referenced using `ls -l ~/Documents/GitHub` or `ls -l ~/documents/github` just as easily. Docker (as far as I have seen) does not run MacOS in a container. Solution: fix the case error in the code. 

I use this on MacOS, so if you find other docker container issues please shoot them over.
